// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: monorepo.sql

package monorepo

import (
	"context"

	"github.com/google/uuid"
)

const CreateBooking = `-- name: CreateBooking :one
INSERT INTO booking (user_id, showtime_id)
VALUES($1, $2) RETURNING user_id
`

type CreateBookingParams struct {
	UserID     int64 `json:"user_id" validate:"required"`
	ShowtimeID int64 `json:"showtime_id" validate:"required"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateBooking, arg.UserID, arg.ShowtimeID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const CreateBookingSeat = `-- name: CreateBookingSeat :one
INSERT INTO booking_seat (booking_id, seat_id, price_paid) VALUES($1,$2,$3) RETURNING id, booking_id, seat_id, price_paid
`

type CreateBookingSeatParams struct {
	BookingID int64   `json:"booking_id" validate:"required"`
	SeatID    int64   `json:"seat_id" validate:"required"`
	PricePaid float64 `json:"price_paid" validate:"required"`
}

func (q *Queries) CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (BookingSeat, error) {
	row := q.db.QueryRow(ctx, CreateBookingSeat, arg.BookingID, arg.SeatID, arg.PricePaid)
	var i BookingSeat
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.SeatID,
		&i.PricePaid,
	)
	return i, err
}

const CreatePayment = `-- name: CreatePayment :one
INSERT INTO payment (booking_id, user_id, payment_method, payment_status, transaction_amount, payment_time)
SELECT 
    b.id,
    b.user_id,
    $1,
    $2,
    b.total_amount,
    NOW()
FROM booking b
WHERE b.id = $3
RETURNING id, user_id, booking_id, payment_method, payment_status, transaction_amount, payment_time
`

type CreatePaymentParams struct {
	PaymentMethod string `json:"payment_method" validate:"required"`
	PaymentStatus string `json:"payment_status" validate:"required"`
	BookingID     int64  `json:"booking_id" validate:"required"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, CreatePayment, arg.PaymentMethod, arg.PaymentStatus, arg.BookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.TransactionAmount,
		&i.PaymentTime,
	)
	return i, err
}

const DeleteBooking = `-- name: DeleteBooking :exec
DELETE FROM booking WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteBooking, id)
	return err
}

const DeleteBookingSeat = `-- name: DeleteBookingSeat :one
DELETE FROM booking_seat WHERE id = $1 RETURNING booking_id
`

func (q *Queries) DeleteBookingSeat(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, DeleteBookingSeat, id)
	var booking_id int64
	err := row.Scan(&booking_id)
	return booking_id, err
}

const GetBooking = `-- name: GetBooking :one
SELECT id, user_id, showtime_id, booking_time, total_amount FROM booking WHERE id =$1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, GetBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.BookingTime,
		&i.TotalAmount,
	)
	return i, err
}

const GetTotalAmmountBooking = `-- name: GetTotalAmmountBooking :one
SELECT total_amount FROM booking WHERE id = $1
`

func (q *Queries) GetTotalAmmountBooking(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRow(ctx, GetTotalAmmountBooking, id)
	var total_amount float64
	err := row.Scan(&total_amount)
	return total_amount, err
}

const ListBooking = `-- name: ListBooking :many
SELECT id, user_id, showtime_id, booking_time, total_amount FROM booking WHERE user_id = $1 ORDER BY booking_time ASC
`

func (q *Queries) ListBooking(ctx context.Context, userID int64) ([]Booking, error) {
	rows, err := q.db.Query(ctx, ListBooking, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.BookingTime,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBookingSeat = `-- name: ListBookingSeat :many
SELECT id, booking_id, seat_id, price_paid FROM booking_seat WHERE booking_id = $1
`

func (q *Queries) ListBookingSeat(ctx context.Context, bookingID int64) ([]BookingSeat, error) {
	rows, err := q.db.Query(ctx, ListBookingSeat, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSeat{}
	for rows.Next() {
		var i BookingSeat
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatID,
			&i.PricePaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPayment = `-- name: ListPayment :many
SELECT id, user_id, booking_id, payment_method, payment_status, transaction_amount, payment_time FROM payment WHERE user_id = $1 ORDER BY payment_time ASC
`

func (q *Queries) ListPayment(ctx context.Context, userID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, ListPayment, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookingID,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.TransactionAmount,
			&i.PaymentTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBookingAmount = `-- name: UpdateBookingAmount :exec
UPDATE booking SET total_amount = (SELECT SUM(price_paid) FROM booking_seat WHERE booking_id = $1) 
WHERE id = $1
`

func (q *Queries) UpdateBookingAmount(ctx context.Context, bookingID int64) error {
	_, err := q.db.Exec(ctx, UpdateBookingAmount, bookingID)
	return err
}
