// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package monorepo

type Cinema struct {
	ID      int64  `json:"id" validate:"required"`
	Name    string `json:"name" validate:"required"`
	Address string `json:"address" validate:"required"`
	City    string `json:"city" validate:"required"`
}

type Genre struct {
	ID   int64  `json:"id" validate:"required"`
	Name string `json:"name" validate:"required"`
}

type ScreenType struct {
	ID   int64  `json:"id" validate:"required"`
	Name string `json:"name" validate:"required"`
}
