CREATE  TABLE "public".booking ( 
	id                   integer  NOT NULL  ,
	user_id              integer  NOT NULL  ,
	showtime_id          integer  NOT NULL  ,
	booking_time         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	total_amount         double precision    ,
	CONSTRAINT pk_booking PRIMARY KEY ( id ),
	CONSTRAINT unq_booking UNIQUE ( user_id, showtime_id ) 
 );
 
 CREATE  TABLE "public".payment ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	booking_id           integer  NOT NULL  ,
	payment_method       varchar(100)  NOT NULL  ,
	payment_status       varchar(10)    ,
	transaction_amount   double precision  NOT NULL  ,
	payment_time         date DEFAULT CURRENT_DATE   ,
	CONSTRAINT pk_payment PRIMARY KEY ( id ),
	CONSTRAINT fk_payment_booking FOREIGN KEY ( booking_id ) REFERENCES "public".booking( id ) ON DELETE CASCADE  
 );
 
 CREATE  TABLE "public".booking_seat ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	booking_id           integer  NOT NULL  ,
	seat_id              integer  NOT NULL  ,
	price_paid           double precision  NOT NULL  ,
	CONSTRAINT pk_booking_seat PRIMARY KEY ( id ),
	CONSTRAINT unq_booking_seat_booking_id UNIQUE ( booking_id, seat_id ) ,
	CONSTRAINT fk_booking_seat_booking FOREIGN KEY ( booking_id ) REFERENCES "public".booking( id ) ON DELETE CASCADE  ,
	CONSTRAINT fk_booking_seat_permission FOREIGN KEY ( seat_id ) REFERENCES "public".seat( id ) ON DELETE CASCADE  
 );