CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public".booking (
    id                   BIGSERIAL NOT NULL,
    user_id              BIGINT NOT NULL,
    showtime_id          BIGINT NOT NULL,
    booking_time         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_amount         double precision,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT unq_booking UNIQUE (user_id, showtime_id)
);

CREATE TABLE "public".payment (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id           BIGSERIAL NOT NULL,
    payment_method       varchar(100) NOT NULL,
    payment_status       varchar(10),
    transaction_amount   double precision NOT NULL,
    payment_time         date DEFAULT CURRENT_DATE,
    CONSTRAINT pk_payment PRIMARY KEY (id),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES "public".booking(id) ON DELETE CASCADE
);

CREATE TABLE "public".booking_seat (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id           BIGSERIAL NOT NULL,
    seat_id              BIGINT NOT NULL,
    price_paid           double precision NOT NULL,
    CONSTRAINT pk_booking_seat PRIMARY KEY (id),
    CONSTRAINT unq_booking_seat_booking_id UNIQUE (booking_id, seat_id),
    CONSTRAINT fk_booking_seat_booking FOREIGN KEY (booking_id) REFERENCES "public".booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_seat_permission FOREIGN KEY (seat_id) REFERENCES "public".seat(id) ON DELETE CASCADE
);
