// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cinema struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

type Film struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Director string `json:"director"`
	GenreID  int32  `json:"genre_id"`
	Duration string `json:"duration"`
}

type Genre struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Screen struct {
	ID           int32  `json:"id"`
	CinemaID     int32  `json:"cinema_id"`
	Name         string `json:"name"`
	ScreenTypeID int32  `json:"screen_type_id"`
}

type ScreenType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Seat struct {
	ID                int32       `json:"id"`
	ScreenID          pgtype.Int4 `json:"screen_id"`
	SeatRow           string      `json:"seat_row"`
	SeatNumber        int32       `json:"seat_number"`
	SeatPriceModifier float64     `json:"seat_price_modifier"`
}

type Showtime struct {
	ID        int32  `json:"id"`
	FilmID    int32  `json:"film_id"`
	ScreenID  int32  `json:"screen_id"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}
