CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public".cinema (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name                 varchar(100) NOT NULL,
    address              text NOT NULL,
    city                 varchar(100) NOT NULL,
    CONSTRAINT pk_cinema PRIMARY KEY (id),
    CONSTRAINT unq_cinema_name UNIQUE (name)
);

CREATE TABLE "public".genre (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name                 varchar(100) NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id),
    CONSTRAINT unq_genre UNIQUE (name)
);


CREATE TABLE "public".screen_type (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name                 varchar(100) NOT NULL,
    CONSTRAINT pk_screen_type PRIMARY KEY (id),
    CONSTRAINT unq_screen_type_name UNIQUE (name)
);

CREATE TABLE "public".film (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title                varchar(100) NOT NULL,
    director             varchar(100) NOT NULL,
    genre_id             BIGINT NOT NULL,
    duration             varchar NOT NULL,
    CONSTRAINT pk_films PRIMARY KEY (id),
    CONSTRAINT unq_film UNIQUE (title),
    CONSTRAINT fk_film_genre FOREIGN KEY (genre_id) REFERENCES "public".genre(id) ON DELETE CASCADE
);

CREATE TABLE "public".screen (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cinema_id            BIGINT NOT NULL,
    name                 varchar(100) NOT NULL,
    screen_type_id       BIGINT NOT NULL,
    CONSTRAINT pk_screen PRIMARY KEY (id),
    CONSTRAINT fk_screen_cinema FOREIGN KEY (cinema_id) REFERENCES "public".cinema(id) ON DELETE CASCADE,
    CONSTRAINT fk_screen_screen FOREIGN KEY (screen_type_id) REFERENCES "public".screen_type(id) ON DELETE CASCADE
);

CREATE TABLE "public".seat (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    screen_id            BIGINT,
    seat_row             char(1) NOT NULL,
    seat_number          integer NOT NULL,
    seat_price_modifier  double precision NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (id),
    CONSTRAINT unq_seat UNIQUE (screen_id, seat_row, seat_number),
    CONSTRAINT fk_seat_screen FOREIGN KEY (screen_id) REFERENCES "public".screen(id) ON DELETE CASCADE
);

CREATE TABLE "public".showtime (
    id                   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id              BIGINT NOT NULL,
    screen_id            BIGINT NOT NULL,
    start_time           varchar(100) NOT NULL,
    base_price           integer NOT NULL,
    CONSTRAINT pk_showtime PRIMARY KEY (id),
    CONSTRAINT fk_showtime_film FOREIGN KEY (film_id) REFERENCES "public".film(id) ON DELETE CASCADE,
    CONSTRAINT fk_showtime_screen FOREIGN KEY (screen_id) REFERENCES "public".screen(id) ON DELETE CASCADE
);

INSERT INTO "public".cinema (name, address, city) VALUES
('CineMaxx Pasuruan', 'Jl. Raya Panglima Sudirman No.10', 'Pasuruan'),
('XXI Plaza Surabaya', 'Jl. Pemuda No.1', 'Surabaya'),
('Trans Studio Premiere', 'Jl. Ahmad Yani No.45', 'Malang'),
('Cinepolis Gresik Mall', 'Jl. Veteran No.7', 'Gresik'),
('XXI Royal Plaza', 'Jl. A. Yani No.16', 'Surabaya'),
('CGV Marvel City', 'Jl. Ngagel No.23', 'Surabaya'),
('Movimax Jember', 'Jl. Gajah Mada No.9', 'Jember'),
('XXI Lippo Plaza Batu', 'Jl. Diponegoro No.22', 'Batu'),
('Cinepolis Tunjungan Plaza', 'Jl. Basuki Rahmat No.8', 'Surabaya'),
('XXI City of Tomorrow', 'Jl. Ahmad Yani No.288', 'Surabaya');

INSERT INTO "public".genre (name) VALUES
('Action'),
('Comedy'),
('Drama'),
('Horror'),
('Romance'),
('Thriller'),
('Animation'),
('Fantasy'),
('Sci-Fi'),
('Documentary');

INSERT INTO "public".screen_type (name) VALUES
('Standard'),
('IMAX'),
('4DX'),
('Dolby Atmos'),
('VIP'),
('Deluxe'),
('Gold Class'),
('Private Box'),
('Premium'),
('Classic');

INSERT INTO "public".film (title, director, genre_id, duration) VALUES
('The Silent Code', 'Christopher Nolan', 6, '02:10:00'),
('Love in Kyoto', 'Makoto Shinkai', 5, '01:55:00'),
('Haunted Forest', 'James Wan', 4, '01:45:00'),
('Beyond the Stars', 'Denis Villeneuve', 9, '02:20:00'),
('The Last Samurai', 'Edward Zwick', 1, '02:30:00'),
('Journey to Evermore', 'Peter Jackson', 8, '02:25:00'),
('Laugh It Up', 'Taika Waititi', 2, '01:40:00'),
('City Tears', 'Greta Gerwig', 3, '02:00:00'),
('The Truth Unfolds', 'David Fincher', 6, '02:15:00'),
('Animal Kingdom', 'Pixar Studio', 7, '01:50:00');

INSERT INTO "public".screen (cinema_id, name, screen_type_id) VALUES
(1, 'Studio 1', 1),
(1, 'Studio 2', 2),
(2, 'Studio 1', 1),
(3, 'Theatre A', 4),
(4, 'Hall 1', 3),
(5, 'Screen 5', 5),
(6, 'IMAX Hall', 2),
(7, 'Screen A', 1),
(8, 'Studio 3', 6),
(9, 'VIP Room', 7);

INSERT INTO "public".seat (screen_id, seat_row, seat_number, seat_price_modifier) VALUES
(1, 'A', 1, 1.0),
(1, 'A', 2, 1.0),
(1, 'B', 1, 1.1),
(2, 'A', 1, 1.2),
(2, 'B', 2, 1.2),
(3, 'C', 3, 1.3),
(4, 'A', 1, 1.5),
(5, 'A', 1, 1.0),
(6, 'B', 2, 1.1),
(7, 'C', 3, 1.0);

INSERT INTO "public".showtime (film_id, screen_id, start_time, base_price) VALUES
(1, 1, '2025-11-05 10:00', 40000),
(2, 1, '2025-11-05 12:30', 45000),
(3, 2, '2025-11-05 14:00', 40000),
(4, 3, '2025-11-05 16:30', 50000),
(5, 4, '2025-11-05 18:00', 60000),
(6, 5, '2025-11-05 20:00', 55000),
(7, 6, '2025-11-05 10:30', 40000),
(8, 7, '2025-11-05 13:00', 45000),
(9, 8, '2025-11-05 15:30', 50000),
(10, 9, '2025-11-05 19:00', 60000);