// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: monorepo.sql

package monorepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateCinema = `-- name: CreateCinema :one
INSERT INTO cinema (name,address,city) VALUES ($1,$2,$3) RETURNING id, name, address, city
`

type CreateCinemaParams struct {
	Name    string `json:"name" validate:"required"`
	Address string `json:"address" validate:"required"`
	City    string `json:"city" validate:"required"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, CreateCinema, arg.Name, arg.Address, arg.City)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const CreateFilm = `-- name: CreateFilm :one
INSERT INTO film (title,director,genre_id,duration) SELECT $1,$2,$3,$4 
WHERE EXISTS(SELECT id FROM genre WHERE id = $3) RETURNING id
`

type CreateFilmParams struct {
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	GenreID  int32  `json:"genre_id" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) CreateFilm(ctx context.Context, arg CreateFilmParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateFilm,
		arg.Title,
		arg.Director,
		arg.GenreID,
		arg.Duration,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CreateGenre = `-- name: CreateGenre :one
INSERT INTO genre (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, CreateGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const CreateScreen = `-- name: CreateScreen :one
INSERT INTO screen (cinema_id, name, screen_type_id)
SELECT $1, $2, $3
WHERE EXISTS (SELECT 1 FROM cinema WHERE id = $1)
  AND EXISTS (SELECT 1 FROM screen_type WHERE id = $3)
RETURNING id
`

type CreateScreenParams struct {
	CinemaID     int32  `json:"cinema_id" validate:"required"`
	Name         string `json:"name" validate:"required"`
	ScreenTypeID int32  `json:"screen_type_id" validate:"required"`
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateScreen, arg.CinemaID, arg.Name, arg.ScreenTypeID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CreateScreenType = `-- name: CreateScreenType :one
INSERT INTO screen_type (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateScreenType(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, CreateScreenType, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CreateSeat = `-- name: CreateSeat :one
INSERT INTO seat (screen_id, seat_row, seat_number, seat_price_modifier)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT 1 FROM screen WHERE id = $1)
RETURNING id
`

type CreateSeatParams struct {
	ScreenID          pgtype.Int4 `json:"screen_id" validate:"required"`
	SeatRow           string      `json:"seat_row" validate:"required"`
	SeatNumber        int32       `json:"seat_number" validate:"required"`
	SeatPriceModifier float64     `json:"seat_price_modifier" validate:"required"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateSeat,
		arg.ScreenID,
		arg.SeatRow,
		arg.SeatNumber,
		arg.SeatPriceModifier,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CreateShowTime = `-- name: CreateShowTime :one
INSERT INTO showtime (film_id, screen_id, start_time, base_price)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT 1 FROM film WHERE id = $1)
  AND EXISTS (SELECT 1 FROM screen WHERE id = $2)
RETURNING id
`

type CreateShowTimeParams struct {
	FilmID    int32  `json:"film_id" validate:"required"`
	ScreenID  int32  `json:"screen_id" validate:"required"`
	StartTime string `json:"start_time" validate:"required"`
	BasePrice int32  `json:"base_price" validate:"required"`
}

func (q *Queries) CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateShowTime,
		arg.FilmID,
		arg.ScreenID,
		arg.StartTime,
		arg.BasePrice,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const DeleteCinema = `-- name: DeleteCinema :exec
DELETE FROM cinema WHERE id = $1
`

func (q *Queries) DeleteCinema(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteCinema, id)
	return err
}

const DeleteFilm = `-- name: DeleteFilm :exec
DELETE FROM film WHERE id = $1
`

func (q *Queries) DeleteFilm(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteFilm, id)
	return err
}

const DeleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genre WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteGenre, id)
	return err
}

const DeleteScreen = `-- name: DeleteScreen :exec
DELETE FROM screen WHERE id = $1
`

func (q *Queries) DeleteScreen(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteScreen, id)
	return err
}

const DeleteScreenType = `-- name: DeleteScreenType :exec
DELETE FROM screen_type WHERE id = $1
`

func (q *Queries) DeleteScreenType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteScreenType, id)
	return err
}

const DeleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seat WHERE id = $1
`

func (q *Queries) DeleteSeat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteSeat, id)
	return err
}

const DeleteShowTime = `-- name: DeleteShowTime :exec
DELETE FROM showtime WHERE id = $1
`

func (q *Queries) DeleteShowTime(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteShowTime, id)
	return err
}

const GetCinema = `-- name: GetCinema :one
SELECT id, name, address, city FROM cinema WHERE id = $1
`

func (q *Queries) GetCinema(ctx context.Context, id int32) (Cinema, error) {
	row := q.db.QueryRow(ctx, GetCinema, id)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const GetFilm = `-- name: GetFilm :one
SELECT film.id, film.title, film.director, genre.name AS genre, film.duration FROM film  
INNER JOIN genre  ON film.genre_id = genre.id WHERE film.id=$1
`

type GetFilmRow struct {
	ID       int32  `json:"id" validate:"required"`
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	Genre    string `json:"genre" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) GetFilm(ctx context.Context, id int32) (GetFilmRow, error) {
	row := q.db.QueryRow(ctx, GetFilm, id)
	var i GetFilmRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Duration,
	)
	return i, err
}

const GetGenre = `-- name: GetGenre :one
SELECT id, name FROM genre WHERE id = $1
`

func (q *Queries) GetGenre(ctx context.Context, id int32) (Genre, error) {
	row := q.db.QueryRow(ctx, GetGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const GetScreen = `-- name: GetScreen :one
SELECT
    screen.id,
    screen.name,
    cinema.name AS cinema_name,
    screen_type.name AS screen_type
FROM screen
INNER JOIN cinema ON screen.cinema_id = cinema.id
INNER JOIN screen_type ON screen.screen_type_id = screen_type.id
WHERE screen.id = $1
`

type GetScreenRow struct {
	ID         int32  `json:"id" validate:"required"`
	Name       string `json:"name" validate:"required"`
	CinemaName string `json:"cinema_name" validate:"required"`
	ScreenType string `json:"screen_type" validate:"required"`
}

func (q *Queries) GetScreen(ctx context.Context, id int32) (GetScreenRow, error) {
	row := q.db.QueryRow(ctx, GetScreen, id)
	var i GetScreenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CinemaName,
		&i.ScreenType,
	)
	return i, err
}

const GetScreenType = `-- name: GetScreenType :one
SELECT id, name FROM screen_type WHERE id = $1
`

func (q *Queries) GetScreenType(ctx context.Context, id int32) (ScreenType, error) {
	row := q.db.QueryRow(ctx, GetScreenType, id)
	var i ScreenType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const GetSeat = `-- name: GetSeat :one
SELECT
    seat.id,
    screen.name AS screen_name,
    seat.seat_row,
    seat.seat_number,
    seat.seat_price_modifier
FROM seat
INNER JOIN screen ON seat.screen_id = screen.id
WHERE seat.id = $1
`

type GetSeatRow struct {
	ID                int32   `json:"id" validate:"required"`
	ScreenName        string  `json:"screen_name" validate:"required"`
	SeatRow           string  `json:"seat_row" validate:"required"`
	SeatNumber        int32   `json:"seat_number" validate:"required"`
	SeatPriceModifier float64 `json:"seat_price_modifier" validate:"required"`
}

func (q *Queries) GetSeat(ctx context.Context, id int32) (GetSeatRow, error) {
	row := q.db.QueryRow(ctx, GetSeat, id)
	var i GetSeatRow
	err := row.Scan(
		&i.ID,
		&i.ScreenName,
		&i.SeatRow,
		&i.SeatNumber,
		&i.SeatPriceModifier,
	)
	return i, err
}

const GetShowTime = `-- name: GetShowTime :one
SELECT
    showtime.id,
    film.title AS film,
    screen.name AS screen,
    showtime.start_time,
    showtime.base_price
FROM showtime
INNER JOIN film ON showtime.film_id = film.id
INNER JOIN screen ON showtime.screen_id = screen.id
WHERE showtime.id = $1
`

type GetShowTimeRow struct {
	ID        int32  `json:"id" validate:"required"`
	Film      string `json:"film" validate:"required"`
	Screen    string `json:"screen" validate:"required"`
	StartTime string `json:"start_time" validate:"required"`
	BasePrice int32  `json:"base_price" validate:"required"`
}

func (q *Queries) GetShowTime(ctx context.Context, id int32) (GetShowTimeRow, error) {
	row := q.db.QueryRow(ctx, GetShowTime, id)
	var i GetShowTimeRow
	err := row.Scan(
		&i.ID,
		&i.Film,
		&i.Screen,
		&i.StartTime,
		&i.BasePrice,
	)
	return i, err
}

const ListCinema = `-- name: ListCinema :many
SELECT id, name, address, city FROM cinema
`

func (q *Queries) ListCinema(ctx context.Context) ([]Cinema, error) {
	rows, err := q.db.Query(ctx, ListCinema)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cinema{}
	for rows.Next() {
		var i Cinema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFilm = `-- name: ListFilm :many
SELECT film.id, film.title, film.director, genre.name AS genre, film.duration FROM film 
INNER JOIN genre ON film.genre_id = genre.id
`

type ListFilmRow struct {
	ID       int32  `json:"id" validate:"required"`
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	Genre    string `json:"genre" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) ListFilm(ctx context.Context) ([]ListFilmRow, error) {
	rows, err := q.db.Query(ctx, ListFilm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilmRow{}
	for rows.Next() {
		var i ListFilmRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.Genre,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGenre = `-- name: ListGenre :many
SELECT id, name FROM genre
`

func (q *Queries) ListGenre(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, ListGenre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScreen = `-- name: ListScreen :many
SELECT
    screen.id,
    screen.name,
    cinema.name AS cinema_name,
    screen_type.name AS screen_type
FROM screen
INNER JOIN cinema ON screen.cinema_id = cinema.id
INNER JOIN screen_type ON screen.screen_type_id = screen_type.id
`

type ListScreenRow struct {
	ID         int32  `json:"id" validate:"required"`
	Name       string `json:"name" validate:"required"`
	CinemaName string `json:"cinema_name" validate:"required"`
	ScreenType string `json:"screen_type" validate:"required"`
}

func (q *Queries) ListScreen(ctx context.Context) ([]ListScreenRow, error) {
	rows, err := q.db.Query(ctx, ListScreen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScreenRow{}
	for rows.Next() {
		var i ListScreenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CinemaName,
			&i.ScreenType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScreenType = `-- name: ListScreenType :many
SELECT id, name FROM screen_type
`

func (q *Queries) ListScreenType(ctx context.Context) ([]ScreenType, error) {
	rows, err := q.db.Query(ctx, ListScreenType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScreenType{}
	for rows.Next() {
		var i ScreenType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSeat = `-- name: ListSeat :many
SELECT
    seat.id,
    screen.name AS screen_name,
    seat.seat_row,
    seat.seat_number,
    seat.seat_price_modifier
FROM seat
INNER JOIN screen ON seat.screen_id = screen.id
`

type ListSeatRow struct {
	ID                int32   `json:"id" validate:"required"`
	ScreenName        string  `json:"screen_name" validate:"required"`
	SeatRow           string  `json:"seat_row" validate:"required"`
	SeatNumber        int32   `json:"seat_number" validate:"required"`
	SeatPriceModifier float64 `json:"seat_price_modifier" validate:"required"`
}

func (q *Queries) ListSeat(ctx context.Context) ([]ListSeatRow, error) {
	rows, err := q.db.Query(ctx, ListSeat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeatRow{}
	for rows.Next() {
		var i ListSeatRow
		if err := rows.Scan(
			&i.ID,
			&i.ScreenName,
			&i.SeatRow,
			&i.SeatNumber,
			&i.SeatPriceModifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListShowTime = `-- name: ListShowTime :many
SELECT
    showtime.id,
    film.title AS film,
    screen.name AS screen,
    showtime.start_time,
    showtime.base_price
FROM showtime
INNER JOIN film ON showtime.film_id = film.id
INNER JOIN screen ON showtime.screen_id = screen.id
`

type ListShowTimeRow struct {
	ID        int32  `json:"id" validate:"required"`
	Film      string `json:"film" validate:"required"`
	Screen    string `json:"screen" validate:"required"`
	StartTime string `json:"start_time" validate:"required"`
	BasePrice int32  `json:"base_price" validate:"required"`
}

func (q *Queries) ListShowTime(ctx context.Context) ([]ListShowTimeRow, error) {
	rows, err := q.db.Query(ctx, ListShowTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowTimeRow{}
	for rows.Next() {
		var i ListShowTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.Film,
			&i.Screen,
			&i.StartTime,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchFilm = `-- name: SearchFilm :many
SELECT film.id, film.title, film.director, genre.name AS genre, film.duration FROM film
INNER JOIN genre  ON film.genre_id = genre.id
WHERE film.title LIKE $1
`

type SearchFilmRow struct {
	ID       int32  `json:"id" validate:"required"`
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	Genre    string `json:"genre" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) SearchFilm(ctx context.Context, title string) ([]SearchFilmRow, error) {
	rows, err := q.db.Query(ctx, SearchFilm, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFilmRow{}
	for rows.Next() {
		var i SearchFilmRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.Genre,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchGenreFilm = `-- name: SearchGenreFilm :many
SELECT film.id, film.title, film.director, genre.name AS genre, film.duration FROM film  
INNER JOIN genre  ON film.genre_id = genre.id WHERE film.genre_id=(SELECT id FROM genre WHERE genre.id = $1)
`

type SearchGenreFilmRow struct {
	ID       int32  `json:"id" validate:"required"`
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	Genre    string `json:"genre" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) SearchGenreFilm(ctx context.Context, id int32) ([]SearchGenreFilmRow, error) {
	rows, err := q.db.Query(ctx, SearchGenreFilm, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGenreFilmRow{}
	for rows.Next() {
		var i SearchGenreFilmRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.Genre,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCinema = `-- name: UpdateCinema :one
UPDATE cinema SET name=$2, address=$3, city=$4 WHERE id =$1 RETURNING id
`

type UpdateCinemaParams struct {
	ID      int32  `json:"id" validate:"required"`
	Name    string `json:"name" validate:"required"`
	Address string `json:"address" validate:"required"`
	City    string `json:"city" validate:"required"`
}

func (q *Queries) UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateCinema,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateFilm = `-- name: UpdateFilm :one
UPDATE film SET title=$2, director=$3, genre_id = $4, duration=$5 WHERE film.id = $1 
AND EXISTS(SELECT id FROM genre WHERE genre.id = $4) RETURNING film.id
`

type UpdateFilmParams struct {
	ID       int32  `json:"id" validate:"required"`
	Title    string `json:"title" validate:"required"`
	Director string `json:"director" validate:"required"`
	GenreID  int32  `json:"genre_id" validate:"required"`
	Duration string `json:"duration" validate:"required"`
}

func (q *Queries) UpdateFilm(ctx context.Context, arg UpdateFilmParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateFilm,
		arg.ID,
		arg.Title,
		arg.Director,
		arg.GenreID,
		arg.Duration,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateGenre = `-- name: UpdateGenre :one
UPDATE genre SET name =$2 WHERE id=$1 RETURNING id
`

type UpdateGenreParams struct {
	ID   int32  `json:"id" validate:"required"`
	Name string `json:"name" validate:"required"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateGenre, arg.ID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateScreen = `-- name: UpdateScreen :one
UPDATE screen
SET cinema_id = $2,
    name = $3,
    screen_type_id = $4
WHERE screen.id = $1
  AND EXISTS (SELECT 1 FROM cinema WHERE id = $2)
  AND EXISTS (SELECT 1 FROM screen_type WHERE id = $4)
RETURNING id
`

type UpdateScreenParams struct {
	ID           int32  `json:"id" validate:"required"`
	CinemaID     int32  `json:"cinema_id" validate:"required"`
	Name         string `json:"name" validate:"required"`
	ScreenTypeID int32  `json:"screen_type_id" validate:"required"`
}

func (q *Queries) UpdateScreen(ctx context.Context, arg UpdateScreenParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateScreen,
		arg.ID,
		arg.CinemaID,
		arg.Name,
		arg.ScreenTypeID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateScreenType = `-- name: UpdateScreenType :one
UPDATE screen_type
SET name = $2
WHERE id = $1
RETURNING id
`

type UpdateScreenTypeParams struct {
	ID   int32  `json:"id" validate:"required"`
	Name string `json:"name" validate:"required"`
}

func (q *Queries) UpdateScreenType(ctx context.Context, arg UpdateScreenTypeParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateScreenType, arg.ID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateSeat = `-- name: UpdateSeat :one
UPDATE seat
SET screen_id = $2,
    seat_row = $3,
    seat_number = $4,
    seat_price_modifier = $5
WHERE seat.id = $1
  AND EXISTS (SELECT 1 FROM screen WHERE id = $2)
RETURNING id
`

type UpdateSeatParams struct {
	ID                int32       `json:"id" validate:"required"`
	ScreenID          pgtype.Int4 `json:"screen_id" validate:"required"`
	SeatRow           string      `json:"seat_row" validate:"required"`
	SeatNumber        int32       `json:"seat_number" validate:"required"`
	SeatPriceModifier float64     `json:"seat_price_modifier" validate:"required"`
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateSeat,
		arg.ID,
		arg.ScreenID,
		arg.SeatRow,
		arg.SeatNumber,
		arg.SeatPriceModifier,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const UpdateShowTime = `-- name: UpdateShowTime :one
UPDATE showtime
SET
    film_id = $2,
    screen_id = $3,
    start_time = $4,
    base_price = $5
WHERE showtime.id = $1
  AND EXISTS (SELECT 1 FROM film WHERE id = $2)
  AND EXISTS (SELECT 1 FROM screen WHERE id = $3)
RETURNING id
`

type UpdateShowTimeParams struct {
	ID        int32  `json:"id" validate:"required"`
	FilmID    int32  `json:"film_id" validate:"required"`
	ScreenID  int32  `json:"screen_id" validate:"required"`
	StartTime string `json:"start_time" validate:"required"`
	BasePrice int32  `json:"base_price" validate:"required"`
}

func (q *Queries) UpdateShowTime(ctx context.Context, arg UpdateShowTimeParams) (int32, error) {
	row := q.db.QueryRow(ctx, UpdateShowTime,
		arg.ID,
		arg.FilmID,
		arg.ScreenID,
		arg.StartTime,
		arg.BasePrice,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
