// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateBooking = `-- name: CreateBooking :one
INSERT INTO booking (user_id, showtime_id, total_amount)
SELECT $1, $2, 0
WHERE EXISTS (SELECT id FROM user_account WHERE id = $1)
  AND EXISTS (SELECT id FROM showtime WHERE id = $2)
RETURNING user_id
`

type CreateBookingParams struct {
	UserID     int32 `json:"user_id"`
	ShowtimeID int32 `json:"showtime_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBooking, arg.UserID, arg.ShowtimeID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const DeleteBooking = `-- name: DeleteBooking :exec
DELETE FROM booking WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBooking, id)
	return err
}

const ListBooking = `-- name: ListBooking :many
SELECT
    booking.id,
    user_account.name AS user_name,
    film.title AS film_name,
    showtime.start_time,
    booking.booking_time,
    booking.total_amount
FROM booking
INNER JOIN user_account ON booking.user_id = user_account.id
INNER JOIN showtime ON booking.showtime_id = showtime.id
INNER JOIN film ON showtime.film_id = film.id
WHERE user_id = $1
`

type ListBookingRow struct {
	ID          int32              `json:"id"`
	UserName    string             `json:"user_name"`
	FilmName    string             `json:"film_name"`
	StartTime   string             `json:"start_time"`
	BookingTime pgtype.Timestamptz `json:"booking_time"`
	TotalAmount pgtype.Float8      `json:"total_amount"`
}

func (q *Queries) ListBooking(ctx context.Context, userID int32) ([]ListBookingRow, error) {
	rows, err := q.db.Query(ctx, ListBooking, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingRow{}
	for rows.Next() {
		var i ListBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.FilmName,
			&i.StartTime,
			&i.BookingTime,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBooking = `-- name: UpdateBooking :one
UPDATE booking SET total_amount = (SELECT SUM(price_paid) FROM booking_seat WHERE booking_id = $1) 
WHERE id = $1 RETURNING total_amount
`

func (q *Queries) UpdateBooking(ctx context.Context, bookingID int32) (pgtype.Float8, error) {
	row := q.db.QueryRow(ctx, UpdateBooking, bookingID)
	var total_amount pgtype.Float8
	err := row.Scan(&total_amount)
	return total_amount, err
}
