// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	ShowtimeID  int32              `json:"showtime_id"`
	BookingTime pgtype.Timestamptz `json:"booking_time"`
	TotalAmount pgtype.Float8      `json:"total_amount"`
}

type BookingSeat struct {
	ID        int32   `json:"id"`
	BookingID int32   `json:"booking_id"`
	SeatID    int32   `json:"seat_id"`
	PricePaid float64 `json:"price_paid"`
}

type Cinema struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

type Film struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Director string `json:"director"`
	GenreID  int32  `json:"genre_id"`
	Duration string `json:"duration"`
}

type Payment struct {
	ID                int32       `json:"id"`
	BookingID         int32       `json:"booking_id"`
	PaymentMethod     string      `json:"payment_method"`
	PaymentStatus     pgtype.Text `json:"payment_status"`
	TransactionAmount float64     `json:"transaction_amount"`
	PaymentTime       pgtype.Date `json:"payment_time"`
}

type Screen struct {
	ID           int32  `json:"id"`
	CinemaID     int32  `json:"cinema_id"`
	Name         string `json:"name"`
	ScreenTypeID int32  `json:"screen_type_id"`
}

type Seat struct {
	ID                int32       `json:"id"`
	ScreenID          pgtype.Int4 `json:"screen_id"`
	SeatRow           string      `json:"seat_row"`
	SeatNumber        int32       `json:"seat_number"`
	SeatPriceModifier float64     `json:"seat_price_modifier"`
}

type Showtime struct {
	ID        int32  `json:"id"`
	FilmID    int32  `json:"film_id"`
	ScreenID  int32  `json:"screen_id"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}

type UserAccount struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
