// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreatePayment = `-- name: CreatePayment :one
INSERT INTO payment (booking_id, payment_method, payment_status, transaction_amount, payment_time)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT id from booking WHERE id = $1) RETURNING id, booking_id, payment_method, payment_status, transaction_amount, payment_time
`

type CreatePaymentParams struct {
	BookingID         int32       `json:"booking_id"`
	PaymentMethod     string      `json:"payment_method"`
	PaymentStatus     pgtype.Text `json:"payment_status"`
	TransactionAmount float64     `json:"transaction_amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, CreatePayment,
		arg.BookingID,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.TransactionAmount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.TransactionAmount,
		&i.PaymentTime,
	)
	return i, err
}

const ListPayment = `-- name: ListPayment :many
SELECT id, booking_id, payment_method, payment_status, transaction_amount, payment_time FROM payment WHERE booking_id = (SELECT id FROM booking WHERE user_id = $1)
`

func (q *Queries) ListPayment(ctx context.Context, userID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, ListPayment, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.TransactionAmount,
			&i.PaymentTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const Report = `-- name: Report :many
SELECT
    F.title AS Film,
    C.city AS Kota,
    COUNT(B.id) AS Total_Tiket_Terjual,
    SUM(P.transaction_amount) AS Total_Pendapatan
FROM
    booking B
JOIN
    payment P ON B.id = P.booking_id
JOIN
    showtime ST ON B.showtime_id = ST.id
JOIN
    film F ON ST.film_id = F.id
JOIN
    screen S ON ST.screen_id = S.id
JOIN
    cinema C ON S.cinema_id = C.id
WHERE
    P.payment_status = 'Success'
GROUP BY
    F.title, C.city
ORDER BY
    Total_Pendapatan DESC
`

type ReportRow struct {
	Film              string `json:"film"`
	Kota              string `json:"kota"`
	TotalTiketTerjual int64  `json:"total_tiket_terjual"`
	TotalPendapatan   int64  `json:"total_pendapatan"`
}

func (q *Queries) Report(ctx context.Context) ([]ReportRow, error) {
	rows, err := q.db.Query(ctx, Report)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRow{}
	for rows.Next() {
		var i ReportRow
		if err := rows.Scan(
			&i.Film,
			&i.Kota,
			&i.TotalTiketTerjual,
			&i.TotalPendapatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
