// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (int32, error)
	CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (int32, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DeleteBooking(ctx context.Context, id int32) error
	DeleteBookingSeat(ctx context.Context, id int32) error
	ListBooking(ctx context.Context, userID int32) ([]ListBookingRow, error)
	ListBookingSeat(ctx context.Context, userID int32) ([]ListBookingSeatRow, error)
	ListPayment(ctx context.Context, userID int32) ([]Payment, error)
	ReportProfit(ctx context.Context) ([]ReportProfitRow, error)
	UpdateBooking(ctx context.Context, bookingID int32) (pgtype.Float8, error)
}

var _ Querier = (*Queries)(nil)
