// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cinema.sql

package repository

import (
	"context"
)

const CreateCinema = `-- name: CreateCinema :one
INSERT INTO cinema (name,address,city) VALUES ($1,$2,$3) RETURNING id, name, address, city
`

type CreateCinemaParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, CreateCinema, arg.Name, arg.Address, arg.City)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const DeleteCinema = `-- name: DeleteCinema :exec
DELETE FROM cinema WHERE id = $1
`

func (q *Queries) DeleteCinema(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteCinema, id)
	return err
}

const GetCinema = `-- name: GetCinema :one
SELECT id, name, address, city FROM cinema WHERE id = $1
`

func (q *Queries) GetCinema(ctx context.Context, id int64) (Cinema, error) {
	row := q.db.QueryRow(ctx, GetCinema, id)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const ListCinema = `-- name: ListCinema :many
SELECT id, name, address, city FROM cinema
`

func (q *Queries) ListCinema(ctx context.Context) ([]Cinema, error) {
	rows, err := q.db.Query(ctx, ListCinema)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cinema{}
	for rows.Next() {
		var i Cinema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCinemaSchedule = `-- name: ListCinemaSchedule :many
SELECT
    c.name AS cinema_name,
    f.title AS film_title,
    st.name AS screen_type,
    sc.name AS screen_name,
    sh.start_time,
    sh.base_price
FROM showtime sh
INNER JOIN film f ON sh.film_id = f.id
INNER JOIN screen sc ON sh.screen_id = sc.id
INNER JOIN screen_type st ON sc.screen_type_id = st.id
INNER JOIN cinema c ON sc.cinema_id = c.id
WHERE c.id = $1
ORDER BY sh.start_time ASC
`

type ListCinemaScheduleRow struct {
	CinemaName string `json:"cinema_name"`
	FilmTitle  string `json:"film_title"`
	ScreenType string `json:"screen_type"`
	ScreenName string `json:"screen_name"`
	StartTime  string `json:"start_time"`
	BasePrice  int32  `json:"base_price"`
}

func (q *Queries) ListCinemaSchedule(ctx context.Context, id int64) ([]ListCinemaScheduleRow, error) {
	rows, err := q.db.Query(ctx, ListCinemaSchedule, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCinemaScheduleRow{}
	for rows.Next() {
		var i ListCinemaScheduleRow
		if err := rows.Scan(
			&i.CinemaName,
			&i.FilmTitle,
			&i.ScreenType,
			&i.ScreenName,
			&i.StartTime,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCinema = `-- name: UpdateCinema :one
UPDATE cinema SET name=$2, address=$3, city=$4 WHERE id =$1 RETURNING id
`

type UpdateCinemaParams struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateCinema,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
