// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cinema.sql

package repository

import (
	"context"
)

const CreateCinema = `-- name: CreateCinema :one
INSERT INTO cinema (name,address,city) VALUES ($1,$2,$3) RETURNING id, name, address, city
`

type CreateCinemaParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, CreateCinema, arg.Name, arg.Address, arg.City)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const DeleteCinema = `-- name: DeleteCinema :exec
DELETE FROM cinema WHERE id = $1
`

func (q *Queries) DeleteCinema(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteCinema, id)
	return err
}

const GetCinema = `-- name: GetCinema :one
SELECT id, name, address, city FROM cinema WHERE id = $1
`

func (q *Queries) GetCinema(ctx context.Context, id int64) (Cinema, error) {
	row := q.db.QueryRow(ctx, GetCinema, id)
	var i Cinema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
	)
	return i, err
}

const ListCinema = `-- name: ListCinema :many
SELECT id, name, address, city FROM cinema
`

func (q *Queries) ListCinema(ctx context.Context) ([]Cinema, error) {
	rows, err := q.db.Query(ctx, ListCinema)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cinema{}
	for rows.Next() {
		var i Cinema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCinema = `-- name: UpdateCinema :one
UPDATE cinema SET name=$2, address=$3, city=$4 WHERE id =$1 RETURNING id
`

type UpdateCinemaParams struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateCinema,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
