// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: genre.sql

package repository

import (
	"context"
)

const CreateGenre = `-- name: CreateGenre :one
INSERT INTO genre (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, CreateGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const DeleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genre WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteGenre, id)
	return err
}

const GetGenre = `-- name: GetGenre :one
SELECT id, name FROM genre WHERE id = $1
`

func (q *Queries) GetGenre(ctx context.Context, id int64) (Genre, error) {
	row := q.db.QueryRow(ctx, GetGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const ListGenre = `-- name: ListGenre :many
SELECT id, name FROM genre
`

func (q *Queries) ListGenre(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, ListGenre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGenre = `-- name: UpdateGenre :one
UPDATE genre SET name =$2 WHERE id=$1 RETURNING id
`

type UpdateGenreParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateGenre, arg.ID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
