// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Cinema struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

type Genre struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type ScreenType struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
