// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error)
	CreateFilm(ctx context.Context, arg CreateFilmParams) (int32, error)
	CreateGenre(ctx context.Context, name string) (Genre, error)
	CreateScreen(ctx context.Context, arg CreateScreenParams) (int32, error)
	CreateScreenType(ctx context.Context, name string) (int32, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (int32, error)
	CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (int32, error)
	DeleteCinema(ctx context.Context, id int32) error
	DeleteFilm(ctx context.Context, id int32) error
	DeleteGenre(ctx context.Context, id int32) error
	DeleteScreen(ctx context.Context, id int32) error
	DeleteScreenType(ctx context.Context, id int32) error
	DeleteSeat(ctx context.Context, id int32) error
	DeleteShowTime(ctx context.Context, id int32) error
	GetCinema(ctx context.Context, id int32) (Cinema, error)
	GetFilm(ctx context.Context, id int32) (GetFilmRow, error)
	GetGenre(ctx context.Context, id int32) (Genre, error)
	GetScreen(ctx context.Context, id int32) (GetScreenRow, error)
	GetScreenType(ctx context.Context, id int32) (ScreenType, error)
	GetSeat(ctx context.Context, id int32) (GetSeatRow, error)
	GetShowTime(ctx context.Context, id int32) (GetShowTimeRow, error)
	ListCinema(ctx context.Context) ([]Cinema, error)
	ListFilm(ctx context.Context) ([]ListFilmRow, error)
	ListGenre(ctx context.Context) ([]Genre, error)
	ListScreen(ctx context.Context) ([]ListScreenRow, error)
	ListScreenType(ctx context.Context) ([]ScreenType, error)
	ListSeat(ctx context.Context) ([]ListSeatRow, error)
	ListShowTime(ctx context.Context) ([]ListShowTimeRow, error)
	SearchFilm(ctx context.Context, title string) ([]SearchFilmRow, error)
	SearchGenreFilm(ctx context.Context, id int32) ([]SearchGenreFilmRow, error)
	UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (int32, error)
	UpdateFilm(ctx context.Context, arg UpdateFilmParams) (int32, error)
	UpdateGenre(ctx context.Context, arg UpdateGenreParams) (int32, error)
	UpdateScreen(ctx context.Context, arg UpdateScreenParams) (int32, error)
	UpdateScreenType(ctx context.Context, arg UpdateScreenTypeParams) (int32, error)
	UpdateSeat(ctx context.Context, arg UpdateSeatParams) (int32, error)
	UpdateShowTime(ctx context.Context, arg UpdateShowTimeParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
