// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: screen.sql

package repository

import (
	"context"
)

const CreateScreen = `-- name: CreateScreen :one
INSERT INTO screen (cinema_id, name, screen_type_id)
SELECT $1, $2, $3
WHERE EXISTS (SELECT 1 FROM cinema WHERE id = $1)
  AND EXISTS (SELECT 1 FROM screen_type WHERE id = $3)
RETURNING id
`

type CreateScreenParams struct {
	CinemaID     int64  `json:"cinema_id"`
	Name         string `json:"name"`
	ScreenTypeID int64  `json:"screen_type_id"`
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateScreen, arg.CinemaID, arg.Name, arg.ScreenTypeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const CreateScreenType = `-- name: CreateScreenType :one
INSERT INTO screen_type (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateScreenType(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, CreateScreenType, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DeleteScreen = `-- name: DeleteScreen :exec
DELETE FROM screen WHERE id = $1
`

func (q *Queries) DeleteScreen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteScreen, id)
	return err
}

const DeleteScreenType = `-- name: DeleteScreenType :exec
DELETE FROM screen_type WHERE id = $1
`

func (q *Queries) DeleteScreenType(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteScreenType, id)
	return err
}

const GetScreen = `-- name: GetScreen :one
SELECT
    screen.id,
    screen.name,
    cinema.name AS cinema_name,
    screen_type.name AS screen_type
FROM screen
INNER JOIN cinema ON screen.cinema_id = cinema.id
INNER JOIN screen_type ON screen.screen_type_id = screen_type.id
WHERE screen.id = $1
`

type GetScreenRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CinemaName string `json:"cinema_name"`
	ScreenType string `json:"screen_type"`
}

func (q *Queries) GetScreen(ctx context.Context, id int64) (GetScreenRow, error) {
	row := q.db.QueryRow(ctx, GetScreen, id)
	var i GetScreenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CinemaName,
		&i.ScreenType,
	)
	return i, err
}

const GetScreenType = `-- name: GetScreenType :one
SELECT id, name FROM screen_type WHERE id = $1
`

func (q *Queries) GetScreenType(ctx context.Context, id int64) (ScreenType, error) {
	row := q.db.QueryRow(ctx, GetScreenType, id)
	var i ScreenType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const ListScreen = `-- name: ListScreen :many
SELECT
    screen.id,
    screen.name,
    cinema.name AS cinema_name,
    screen_type.name AS screen_type
FROM screen
INNER JOIN cinema ON screen.cinema_id = cinema.id
INNER JOIN screen_type ON screen.screen_type_id = screen_type.id
`

type ListScreenRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CinemaName string `json:"cinema_name"`
	ScreenType string `json:"screen_type"`
}

func (q *Queries) ListScreen(ctx context.Context) ([]ListScreenRow, error) {
	rows, err := q.db.Query(ctx, ListScreen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScreenRow{}
	for rows.Next() {
		var i ListScreenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CinemaName,
			&i.ScreenType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScreenType = `-- name: ListScreenType :many
SELECT id, name FROM screen_type
`

func (q *Queries) ListScreenType(ctx context.Context) ([]ScreenType, error) {
	rows, err := q.db.Query(ctx, ListScreenType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScreenType{}
	for rows.Next() {
		var i ScreenType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateScreen = `-- name: UpdateScreen :one
UPDATE screen
SET cinema_id = $2,
    name = $3,
    screen_type_id = $4
WHERE screen.id = $1
  AND EXISTS (SELECT 1 FROM cinema WHERE id = $2)
  AND EXISTS (SELECT 1 FROM screen_type WHERE id = $4)
RETURNING id
`

type UpdateScreenParams struct {
	ID           int64  `json:"id"`
	CinemaID     int64  `json:"cinema_id"`
	Name         string `json:"name"`
	ScreenTypeID int64  `json:"screen_type_id"`
}

func (q *Queries) UpdateScreen(ctx context.Context, arg UpdateScreenParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateScreen,
		arg.ID,
		arg.CinemaID,
		arg.Name,
		arg.ScreenTypeID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdateScreenType = `-- name: UpdateScreenType :one
UPDATE screen_type SET name = $2 WHERE id = $1 RETURNING id
`

type UpdateScreenTypeParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateScreenType(ctx context.Context, arg UpdateScreenTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateScreenType, arg.ID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
