// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seat.sql

package repository

import (
	"context"
)

const CreateSeat = `-- name: CreateSeat :one
INSERT INTO seat (screen_id, seat_row, seat_number, seat_price_modifier)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT 1 FROM screen WHERE id = $1)
RETURNING id
`

type CreateSeatParams struct {
	ScreenID          int64   `json:"screen_id"`
	SeatRow           string  `json:"seat_row"`
	SeatNumber        int32   `json:"seat_number"`
	SeatPriceModifier float64 `json:"seat_price_modifier"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateSeat,
		arg.ScreenID,
		arg.SeatRow,
		arg.SeatNumber,
		arg.SeatPriceModifier,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DeleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seat WHERE id = $1
`

func (q *Queries) DeleteSeat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteSeat, id)
	return err
}

const GetSeat = `-- name: GetSeat :one
SELECT
    seat.id,
    screen.name AS screen_name,
    seat.seat_row,
    seat.seat_number,
    seat.seat_price_modifier
FROM seat
INNER JOIN screen ON seat.screen_id = screen.id
WHERE seat.id = $1
`

type GetSeatRow struct {
	ID                int64   `json:"id"`
	ScreenName        string  `json:"screen_name"`
	SeatRow           string  `json:"seat_row"`
	SeatNumber        int32   `json:"seat_number"`
	SeatPriceModifier float64 `json:"seat_price_modifier"`
}

func (q *Queries) GetSeat(ctx context.Context, id int64) (GetSeatRow, error) {
	row := q.db.QueryRow(ctx, GetSeat, id)
	var i GetSeatRow
	err := row.Scan(
		&i.ID,
		&i.ScreenName,
		&i.SeatRow,
		&i.SeatNumber,
		&i.SeatPriceModifier,
	)
	return i, err
}

const ListSeat = `-- name: ListSeat :many
SELECT
    seat.id,
    screen.name AS screen_name,
    seat.seat_row,
    seat.seat_number,
    seat.seat_price_modifier
FROM seat
INNER JOIN screen ON seat.screen_id = screen.id
`

type ListSeatRow struct {
	ID                int64   `json:"id"`
	ScreenName        string  `json:"screen_name"`
	SeatRow           string  `json:"seat_row"`
	SeatNumber        int32   `json:"seat_number"`
	SeatPriceModifier float64 `json:"seat_price_modifier"`
}

func (q *Queries) ListSeat(ctx context.Context) ([]ListSeatRow, error) {
	rows, err := q.db.Query(ctx, ListSeat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeatRow{}
	for rows.Next() {
		var i ListSeatRow
		if err := rows.Scan(
			&i.ID,
			&i.ScreenName,
			&i.SeatRow,
			&i.SeatNumber,
			&i.SeatPriceModifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SeatPrice = `-- name: SeatPrice :one
SELECT (showtime.base_price * seat.seat_price_modifier) AS seat_price 
FROM showtime JOIN seat ON showtime.screen_id = seat.screen_id 
WHERE showtime.id = $1 AND seat.id = $2
`

type SeatPriceParams struct {
	ShowtimeID int64 `json:"showtime_id"`
	SeatID     int64 `json:"seat_id"`
}

func (q *Queries) SeatPrice(ctx context.Context, arg SeatPriceParams) (int64, error) {
	row := q.db.QueryRow(ctx, SeatPrice, arg.ShowtimeID, arg.SeatID)
	var seat_price int64
	err := row.Scan(&seat_price)
	return seat_price, err
}

const UpdateSeat = `-- name: UpdateSeat :one
UPDATE seat
SET screen_id = $2,
    seat_row = $3,
    seat_number = $4,
    seat_price_modifier = $5
WHERE seat.id = $1
  AND EXISTS (SELECT 1 FROM screen WHERE id = $2)
RETURNING id
`

type UpdateSeatParams struct {
	ID                int64   `json:"id"`
	ScreenID          int64   `json:"screen_id"`
	SeatRow           string  `json:"seat_row"`
	SeatNumber        int32   `json:"seat_number"`
	SeatPriceModifier float64 `json:"seat_price_modifier"`
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateSeat,
		arg.ID,
		arg.ScreenID,
		arg.SeatRow,
		arg.SeatNumber,
		arg.SeatPriceModifier,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
