// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: showtime.sql

package repository

import (
	"context"
)

const CreateShowTime = `-- name: CreateShowTime :one
INSERT INTO showtime (film_id, screen_id, start_time, base_price)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT 1 FROM film WHERE id = $1)
  AND EXISTS (SELECT 1 FROM screen WHERE id = $2)
RETURNING id
`

type CreateShowTimeParams struct {
	FilmID    int64  `json:"film_id"`
	ScreenID  int64  `json:"screen_id"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}

func (q *Queries) CreateShowTime(ctx context.Context, arg CreateShowTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateShowTime,
		arg.FilmID,
		arg.ScreenID,
		arg.StartTime,
		arg.BasePrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DeleteShowTime = `-- name: DeleteShowTime :exec
DELETE FROM showtime WHERE id = $1
`

func (q *Queries) DeleteShowTime(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteShowTime, id)
	return err
}

const GetShowTime = `-- name: GetShowTime :one
SELECT
    showtime.id,
    film.title AS film,
    screen.name AS screen,
    showtime.start_time,
    showtime.base_price
FROM showtime
INNER JOIN film ON showtime.film_id = film.id
INNER JOIN screen ON showtime.screen_id = screen.id
WHERE showtime.id = $1
`

type GetShowTimeRow struct {
	ID        int64  `json:"id"`
	Film      string `json:"film"`
	Screen    string `json:"screen"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}

func (q *Queries) GetShowTime(ctx context.Context, id int64) (GetShowTimeRow, error) {
	row := q.db.QueryRow(ctx, GetShowTime, id)
	var i GetShowTimeRow
	err := row.Scan(
		&i.ID,
		&i.Film,
		&i.Screen,
		&i.StartTime,
		&i.BasePrice,
	)
	return i, err
}

const ListShowTime = `-- name: ListShowTime :many
SELECT
    showtime.id,
    film.title AS film,
    screen.name AS screen,
    showtime.start_time,
    showtime.base_price
FROM showtime
INNER JOIN film ON showtime.film_id = film.id
INNER JOIN screen ON showtime.screen_id = screen.id
`

type ListShowTimeRow struct {
	ID        int64  `json:"id"`
	Film      string `json:"film"`
	Screen    string `json:"screen"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}

func (q *Queries) ListShowTime(ctx context.Context) ([]ListShowTimeRow, error) {
	rows, err := q.db.Query(ctx, ListShowTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowTimeRow{}
	for rows.Next() {
		var i ListShowTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.Film,
			&i.Screen,
			&i.StartTime,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateShowTime = `-- name: UpdateShowTime :one
UPDATE showtime
SET
    film_id = $2,
    screen_id = $3,
    start_time = $4,
    base_price = $5
WHERE showtime.id = $1
  AND EXISTS (SELECT 1 FROM film WHERE id = $2)
  AND EXISTS (SELECT 1 FROM screen WHERE id = $3)
RETURNING id
`

type UpdateShowTimeParams struct {
	ID        int64  `json:"id"`
	FilmID    int64  `json:"film_id"`
	ScreenID  int64  `json:"screen_id"`
	StartTime string `json:"start_time"`
	BasePrice int32  `json:"base_price"`
}

func (q *Queries) UpdateShowTime(ctx context.Context, arg UpdateShowTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateShowTime,
		arg.ID,
		arg.FilmID,
		arg.ScreenID,
		arg.StartTime,
		arg.BasePrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
