// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package repository

import (
	"context"
)

const CreateBooking = `-- name: CreateBooking :one
INSERT INTO booking (id,user_id, showtime_id)
VALUES($1, $2, $3) RETURNING id, user_id, showtime_id, booking_time, total_amount
`

type CreateBookingParams struct {
	ID         int64 `json:"id"`
	UserID     int64 `json:"user_id"`
	ShowtimeID int64 `json:"showtime_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, CreateBooking, arg.ID, arg.UserID, arg.ShowtimeID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.BookingTime,
		&i.TotalAmount,
	)
	return i, err
}

const DeleteBooking = `-- name: DeleteBooking :exec
DELETE FROM booking WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteBooking, id)
	return err
}

const GetBooking = `-- name: GetBooking :one
SELECT id, user_id, showtime_id, booking_time, total_amount FROM booking WHERE id =$1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, GetBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.BookingTime,
		&i.TotalAmount,
	)
	return i, err
}

const GetTotalAmmountBooking = `-- name: GetTotalAmmountBooking :one
SELECT total_amount FROM booking WHERE id = $1
`

func (q *Queries) GetTotalAmmountBooking(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRow(ctx, GetTotalAmmountBooking, id)
	var total_amount float64
	err := row.Scan(&total_amount)
	return total_amount, err
}

const ListBooking = `-- name: ListBooking :many
SELECT id, user_id, showtime_id, booking_time, total_amount FROM booking WHERE user_id = $1 ORDER BY booking_time ASC
`

func (q *Queries) ListBooking(ctx context.Context, userID int64) ([]Booking, error) {
	rows, err := q.db.Query(ctx, ListBooking, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.BookingTime,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBookingAmount = `-- name: UpdateBookingAmount :exec
UPDATE booking SET total_amount = (SELECT SUM(price_paid) FROM booking_seat WHERE booking_id = $1) 
WHERE id = $1
`

func (q *Queries) UpdateBookingAmount(ctx context.Context, bookingID int64) error {
	_, err := q.db.Exec(ctx, UpdateBookingAmount, bookingID)
	return err
}
