// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking_seat.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const CreateBookingSeat = `-- name: CreateBookingSeat :one
INSERT INTO booking_seat (booking_id, seat_id, price_paid) VALUES($1,$2,$3) RETURNING id, booking_id, seat_id, price_paid
`

type CreateBookingSeatParams struct {
	BookingID int64   `json:"booking_id"`
	SeatID    int64   `json:"seat_id"`
	PricePaid float64 `json:"price_paid"`
}

func (q *Queries) CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (BookingSeat, error) {
	row := q.db.QueryRow(ctx, CreateBookingSeat, arg.BookingID, arg.SeatID, arg.PricePaid)
	var i BookingSeat
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.SeatID,
		&i.PricePaid,
	)
	return i, err
}

const DeleteBookingSeat = `-- name: DeleteBookingSeat :one
DELETE FROM booking_seat WHERE id = $1 RETURNING booking_id
`

func (q *Queries) DeleteBookingSeat(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, DeleteBookingSeat, id)
	var booking_id int64
	err := row.Scan(&booking_id)
	return booking_id, err
}

const ListBookingSeat = `-- name: ListBookingSeat :many
SELECT id, booking_id, seat_id, price_paid FROM booking_seat WHERE booking_id = $1
`

func (q *Queries) ListBookingSeat(ctx context.Context, bookingID int64) ([]BookingSeat, error) {
	rows, err := q.db.Query(ctx, ListBookingSeat, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSeat{}
	for rows.Next() {
		var i BookingSeat
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatID,
			&i.PricePaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
