// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: booking_seat.sql

package repository

import (
	"context"
)

const CreateBookingSeat = `-- name: CreateBookingSeat :one
INSERT INTO booking_seat (booking_id, seat_id, price_paid) SELECT $1,$2,$3
WHERE EXISTS (SELECT id FROM booking WHERE id = $1 AND user_id = $4) 
RETURNING booking_id
`

type CreateBookingSeatParams struct {
	BookingID int32   `json:"booking_id"`
	SeatID    int32   `json:"seat_id"`
	PricePaid float64 `json:"price_paid"`
	UserID    int32   `json:"user_id"`
}

func (q *Queries) CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBookingSeat,
		arg.BookingID,
		arg.SeatID,
		arg.PricePaid,
		arg.UserID,
	)
	var booking_id int32
	err := row.Scan(&booking_id)
	return booking_id, err
}

const DeleteBookingSeat = `-- name: DeleteBookingSeat :exec
DELETE FROM booking_seat WHERE id = $1
`

func (q *Queries) DeleteBookingSeat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBookingSeat, id)
	return err
}

const ListBookingSeat = `-- name: ListBookingSeat :many
SELECT booking_seat.id, booking_seat.booking_id, seat.seat_row AS seat_row, seat.seat_number AS seat_number 
FROM booking_seat 
INNER JOIN seat ON booking_seat.seat_id = seat.id
WHERE booking_seat.booking_id = (SELECT id FROM booking WHERE user_id = $1)
`

type ListBookingSeatRow struct {
	ID         int32  `json:"id"`
	BookingID  int32  `json:"booking_id"`
	SeatRow    string `json:"seat_row"`
	SeatNumber int32  `json:"seat_number"`
}

func (q *Queries) ListBookingSeat(ctx context.Context, userID int32) ([]ListBookingSeatRow, error) {
	rows, err := q.db.Query(ctx, ListBookingSeat, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingSeatRow{}
	for rows.Next() {
		var i ListBookingSeatRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatRow,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
