// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                int32       `json:"id"`
	BookingID         int32       `json:"booking_id"`
	PaymentMethod     string      `json:"payment_method"`
	PaymentStatus     pgtype.Text `json:"payment_status"`
	TransactionAmount float64     `json:"transaction_amount"`
	PaymentTime       pgtype.Date `json:"payment_time"`
}
