// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	ShowtimeID  int64     `json:"showtime_id"`
	BookingTime time.Time `json:"booking_time"`
	TotalAmount float64   `json:"total_amount"`
}

type BookingSeat struct {
	ID        uuid.UUID `json:"id"`
	BookingID int64     `json:"booking_id"`
	SeatID    int64     `json:"seat_id"`
	PricePaid float64   `json:"price_paid"`
}

type Payment struct {
	ID                int64     `json:"id"`
	UserID            int64     `json:"user_id"`
	BookingID         int64     `json:"booking_id"`
	PaymentMethod     string    `json:"payment_method"`
	PaymentStatus     string    `json:"payment_status"`
	TransactionAmount float64   `json:"transaction_amount"`
	PaymentTime       time.Time `json:"payment_time"`
}
