// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package monorepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                int32       `json:"id" validate:"required"`
	BookingID         int32       `json:"booking_id" validate:"required"`
	PaymentMethod     string      `json:"payment_method" validate:"required"`
	PaymentStatus     pgtype.Text `json:"payment_status" validate:"required"`
	TransactionAmount float64     `json:"transaction_amount" validate:"required"`
	PaymentTime       pgtype.Date `json:"payment_time" validate:"required"`
}
