// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package monorepo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID          int64              `json:"id" validate:"required"`
	UserID      int64              `json:"user_id" validate:"required"`
	ShowtimeID  int64              `json:"showtime_id" validate:"required"`
	BookingTime pgtype.Timestamptz `json:"booking_time" validate:"required"`
	TotalAmount pgtype.Float8      `json:"total_amount" validate:"required"`
}

type BookingSeat struct {
	ID        uuid.UUID `json:"id" validate:"required"`
	BookingID int64     `json:"booking_id" validate:"required"`
	SeatID    int64     `json:"seat_id" validate:"required"`
	PricePaid float64   `json:"price_paid" validate:"required"`
}

type Payment struct {
	ID                int64              `json:"id" validate:"required"`
	UserID            int64              `json:"user_id" validate:"required"`
	BookingID         int64              `json:"booking_id" validate:"required"`
	PaymentMethod     string             `json:"payment_method" validate:"required"`
	PaymentStatus     pgtype.Text        `json:"payment_status" validate:"required"`
	TransactionAmount float64            `json:"transaction_amount" validate:"required"`
	PaymentTime       pgtype.Timestamptz `json:"payment_time" validate:"required"`
}
