// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: monorepo.sql

package monorepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateBooking = `-- name: CreateBooking :one
INSERT INTO booking (user_id, showtime_id, total_amount)
SELECT $1, $2, 0
WHERE EXISTS (SELECT id FROM user_account WHERE id = $1)
  AND EXISTS (SELECT id FROM showtime WHERE id = $2)
RETURNING user_id
`

type CreateBookingParams struct {
	UserID     int32 `json:"user_id" validate:"required"`
	ShowtimeID int32 `json:"showtime_id" validate:"required"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBooking, arg.UserID, arg.ShowtimeID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const CreateBookingSeat = `-- name: CreateBookingSeat :one
INSERT INTO booking_seat (booking_id, seat_id, price_paid) SELECT $1,$2,$3
WHERE EXISTS (SELECT id FROM booking WHERE id = $1 AND user_id = $4) 
RETURNING booking_id
`

type CreateBookingSeatParams struct {
	BookingID int32   `json:"booking_id" validate:"required"`
	SeatID    int32   `json:"seat_id" validate:"required"`
	PricePaid float64 `json:"price_paid" validate:"required"`
	UserID    int32   `json:"user_id" validate:"required"`
}

func (q *Queries) CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBookingSeat,
		arg.BookingID,
		arg.SeatID,
		arg.PricePaid,
		arg.UserID,
	)
	var booking_id int32
	err := row.Scan(&booking_id)
	return booking_id, err
}

const CreatePayment = `-- name: CreatePayment :one
INSERT INTO payment (booking_id, payment_method, payment_status, transaction_amount, payment_time)
SELECT 
    b.id,
    $2 AS payment_method,
    "Success" AS payment_status,
    b.total_amount AS transaction_amount,
    NOW() AS payment_time
FROM booking b
WHERE b.id = $1
RETURNING id, booking_id, payment_method, payment_status, transaction_amount, payment_time
`

type CreatePaymentParams struct {
	ID            int32  `json:"id" validate:"required"`
	PaymentMethod string `json:"payment_method" validate:"required"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, CreatePayment, arg.ID, arg.PaymentMethod)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.TransactionAmount,
		&i.PaymentTime,
	)
	return i, err
}

const DeleteBooking = `-- name: DeleteBooking :exec
DELETE FROM booking WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBooking, id)
	return err
}

const DeleteBookingSeat = `-- name: DeleteBookingSeat :exec
DELETE FROM booking_seat WHERE id = $1
`

func (q *Queries) DeleteBookingSeat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBookingSeat, id)
	return err
}

const ListBooking = `-- name: ListBooking :many
SELECT
    booking.id,
    user_account.name AS user_name,
    film.title AS film_name,
    showtime.start_time,
    booking.booking_time,
    booking.total_amount
FROM booking
INNER JOIN user_account ON booking.user_id = user_account.id
INNER JOIN showtime ON booking.showtime_id = showtime.id
INNER JOIN film ON showtime.film_id = film.id
WHERE user_id = $1
`

type ListBookingRow struct {
	ID          int32              `json:"id" validate:"required"`
	UserName    string             `json:"user_name"`
	FilmName    string             `json:"film_name"`
	StartTime   string             `json:"start_time"`
	BookingTime pgtype.Timestamptz `json:"booking_time" validate:"required"`
	TotalAmount pgtype.Float8      `json:"total_amount" validate:"required"`
}

func (q *Queries) ListBooking(ctx context.Context, userID int32) ([]ListBookingRow, error) {
	rows, err := q.db.Query(ctx, ListBooking, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingRow{}
	for rows.Next() {
		var i ListBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.FilmName,
			&i.StartTime,
			&i.BookingTime,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBookingSeat = `-- name: ListBookingSeat :many
SELECT booking_seat.id, booking_seat.booking_id, seat.seat_row AS seat_row, seat.seat_number AS seat_number 
FROM booking_seat 
INNER JOIN seat ON booking_seat.seat_id = seat.id
WHERE booking_seat.booking_id = (SELECT id FROM booking WHERE user_id = $1)
`

type ListBookingSeatRow struct {
	ID         int32  `json:"id" validate:"required"`
	BookingID  int32  `json:"booking_id" validate:"required"`
	SeatRow    string `json:"seat_row"`
	SeatNumber int32  `json:"seat_number"`
}

func (q *Queries) ListBookingSeat(ctx context.Context, userID int32) ([]ListBookingSeatRow, error) {
	rows, err := q.db.Query(ctx, ListBookingSeat, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingSeatRow{}
	for rows.Next() {
		var i ListBookingSeatRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatRow,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPayment = `-- name: ListPayment :many
SELECT id, booking_id, payment_method, payment_status, transaction_amount, payment_time FROM payment WHERE booking_id = (SELECT id FROM booking WHERE user_id = $1)
`

func (q *Queries) ListPayment(ctx context.Context, userID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, ListPayment, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.TransactionAmount,
			&i.PaymentTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReportProfit = `-- name: ReportProfit :many
SELECT
    F.title AS Film,
    C.city AS Kota,
    COUNT(B.id) AS Total_Tiket_Terjual,
    SUM(P.transaction_amount) AS Total_Pendapatan
FROM
    booking B
JOIN
    payment P ON B.id = P.booking_id
JOIN
    showtime ST ON B.showtime_id = ST.id
JOIN
    film F ON ST.film_id = F.id
JOIN
    screen S ON ST.screen_id = S.id
JOIN
    cinema C ON S.cinema_id = C.id
WHERE
    P.payment_status = 'Success'
GROUP BY
    F.title, C.city
ORDER BY
    Total_Pendapatan DESC
`

type ReportProfitRow struct {
	Film              string `json:"film"`
	Kota              string `json:"kota"`
	TotalTiketTerjual int64  `json:"total_tiket_terjual"`
	TotalPendapatan   int64  `json:"total_pendapatan"`
}

func (q *Queries) ReportProfit(ctx context.Context) ([]ReportProfitRow, error) {
	rows, err := q.db.Query(ctx, ReportProfit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportProfitRow{}
	for rows.Next() {
		var i ReportProfitRow
		if err := rows.Scan(
			&i.Film,
			&i.Kota,
			&i.TotalTiketTerjual,
			&i.TotalPendapatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBookingAmount = `-- name: UpdateBookingAmount :exec
UPDATE booking SET total_amount = (SELECT SUM(price_paid) FROM booking_seat WHERE booking_id = $1) 
WHERE id = $1
`

func (q *Queries) UpdateBookingAmount(ctx context.Context, bookingID int32) error {
	_, err := q.db.Exec(ctx, UpdateBookingAmount, bookingID)
	return err
}
