// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: monorepo.sql

package monorepo

import (
	"context"
)

const CreateBooking = `-- name: CreateBooking :one
INSERT INTO booking (user_id, showtime_id, total_amount)
VALUES($1, $2, 0) RETURNING user_id
`

type CreateBookingParams struct {
	UserID     int32 `json:"user_id" validate:"required"`
	ShowtimeID int32 `json:"showtime_id" validate:"required"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBooking, arg.UserID, arg.ShowtimeID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const CreateBookingSeat = `-- name: CreateBookingSeat :one
INSERT INTO booking_seat (booking_id, seat_id, price_paid) VALUES($1,$2,$3) RETURNING booking_id
`

type CreateBookingSeatParams struct {
	BookingID int32   `json:"booking_id" validate:"required"`
	SeatID    int32   `json:"seat_id" validate:"required"`
	PricePaid float64 `json:"price_paid" validate:"required"`
}

func (q *Queries) CreateBookingSeat(ctx context.Context, arg CreateBookingSeatParams) (int32, error) {
	row := q.db.QueryRow(ctx, CreateBookingSeat, arg.BookingID, arg.SeatID, arg.PricePaid)
	var booking_id int32
	err := row.Scan(&booking_id)
	return booking_id, err
}

const CreatePayment = `-- name: CreatePayment :one
INSERT INTO payment (booking_id, payment_method, payment_status, transaction_amount, payment_time)
SELECT 
    b.id,
    $2 AS payment_method,
    "Success" AS payment_status,
    b.total_amount AS transaction_amount,
    NOW() AS payment_time
FROM booking
WHERE booking.id = $1
RETURNING id, booking_id, payment_method, payment_status, transaction_amount, payment_time
`

type CreatePaymentParams struct {
	ID            int32  `json:"id" validate:"required"`
	PaymentMethod string `json:"payment_method" validate:"required"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, CreatePayment, arg.ID, arg.PaymentMethod)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.TransactionAmount,
		&i.PaymentTime,
	)
	return i, err
}

const DeleteBooking = `-- name: DeleteBooking :exec
DELETE FROM booking WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBooking, id)
	return err
}

const DeleteBookingSeat = `-- name: DeleteBookingSeat :exec
DELETE FROM booking_seat WHERE id = $1
`

func (q *Queries) DeleteBookingSeat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBookingSeat, id)
	return err
}

const ListBooking = `-- name: ListBooking :many
SELECT id, user_id, showtime_id, booking_time, total_amount FROM booking WHERE user_id = $1
`

func (q *Queries) ListBooking(ctx context.Context, userID int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, ListBooking, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.BookingTime,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBookingSeat = `-- name: ListBookingSeat :many
SELECT id, booking_id, seat_id, price_paid FROM booking_seat WHERE booking_id = $1
`

func (q *Queries) ListBookingSeat(ctx context.Context, bookingID int32) ([]BookingSeat, error) {
	rows, err := q.db.Query(ctx, ListBookingSeat, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSeat{}
	for rows.Next() {
		var i BookingSeat
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatID,
			&i.PricePaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPayment = `-- name: ListPayment :many
SELECT id, booking_id, payment_method, payment_status, transaction_amount, payment_time FROM payment WHERE booking_id = (SELECT id FROM booking WHERE user_id = $1)
`

func (q *Queries) ListPayment(ctx context.Context, userID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, ListPayment, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.TransactionAmount,
			&i.PaymentTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBookingAmount = `-- name: UpdateBookingAmount :exec
UPDATE booking SET total_amount = (SELECT SUM(price_paid) FROM booking_seat WHERE booking_id = $1) 
WHERE id = $1
`

func (q *Queries) UpdateBookingAmount(ctx context.Context, bookingID int32) error {
	_, err := q.db.Exec(ctx, UpdateBookingAmount, bookingID)
	return err
}
