// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Permission struct {
	ID        int64     `json:"id" validate:"required"`
	Name      string    `json:"name" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`
}

type UserAccount struct {
	ID        int64     `json:"id" validate:"required"`
	Name      string    `json:"name" validate:"required"`
	Email     string    `json:"email" validate:"required,email"`
	Password  string    `json:"password" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`
}

type UserProfile struct {
	ID        int64     `json:"id" validate:"required"`
	UserID    int64     `json:"user_id" validate:"required"`
	Age       *int64    `json:"age" validate:"required"`
	Phone     *int64    `json:"phone" validate:"required"`
	District  *string   `json:"district" validate:"required"`
	City      *string   `json:"city" validate:"required"`
	Country   *string   `json:"country" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`
}
