// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        int32     `json:"id" validate:"required"`
	Name      string    `json:"name" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`
}

type UserAccount struct {
	ID        int32     `json:"id" validate:"required"`
	Name      string    `json:"name" validate:"required"`
	Email     string    `json:"email" validate:"required"`
	Password  string    `json:"password" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`
}

type UserProfile struct {
	ID        int32       `json:"id" validate:"required"`
	UserID    int32       `json:"user_id" validate:"required"`
	Age       pgtype.Int4 `json:"age" validate:"required"`
	Phone     pgtype.Int4 `json:"phone" validate:"required"`
	District  pgtype.Text `json:"district" validate:"required"`
	City      pgtype.Text `json:"city" validate:"required"`
	Country   pgtype.Text `json:"country" validate:"required"`
	CreatedAt time.Time   `json:"created_at" validate:"required"`
}
