// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	AddPermissionRole(ctx context.Context, arg AddPermissionRoleParams) error
	AllRoleClient(ctx context.Context, idUser int32) ([]AllRoleClientRow, error)
	CreatePermission(ctx context.Context, name string) error
	CreateProfile(ctx context.Context, userID int32) error
	CreateRole(ctx context.Context, name string) (int32, error)
	CreateRoleClient(ctx context.Context, arg CreateRoleClientParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteClient(ctx context.Context, id int32) error
	DeletePermission(ctx context.Context, id int32) error
	DeletePermissionRole(ctx context.Context, idRole int32) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteRoleClient(ctx context.Context, idUser int32) error
	FindEmail(ctx context.Context, email string) (FindEmailRow, error)
	GetClient(ctx context.Context, id int32) (GetClientRow, error)
	GetPermission(ctx context.Context, id int32) (GetPermissionRow, error)
	GetPermissionRole(ctx context.Context, idRole int32) ([]GetPermissionRoleRow, error)
	GetProfile(ctx context.Context, id int32) (GetProfileRow, error)
	GetRole(ctx context.Context, id int32) (GetRoleRow, error)
	GetRoleClient(ctx context.Context, idUser int32) ([]GetRoleClientRow, error)
	ListClient(ctx context.Context) ([]ListClientRow, error)
	ListPermission(ctx context.Context) ([]Permission, error)
	ListPermissionRole(ctx context.Context, dollar_1 []int32) ([]ListPermissionRoleRow, error)
	ListRole(ctx context.Context) ([]ListRoleRow, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdatePermissionRole(ctx context.Context, arg UpdatePermissionRoleParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateRoleClient(ctx context.Context, arg UpdateRoleClientParams) error
	VerifyPermission(ctx context.Context, dollar_1 []int32) ([]int32, error)
	VerifyRole(ctx context.Context, dollar_1 []int32) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
